In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re
from datetime import datetime
from urllib.parse import urljoin, urlparse
from FragranticaScraper import FragranticaScraper

In [1]:
import secrets
from enum import Enum
import datetime
from fastapi.security import HTTPBasic 
import psycopg2
import os
import pandas as pd
from json import loads
import json
import re
import numpy as np
from functools import partial
from urllib.parse import urlparse, parse_qs
from typing import Annotated

In [2]:
os.environ["DATABASE_NAME"] = "postgres"
os.environ["DATABASE_USER"] = "streetlives"
os.environ["DATABASE_PASSWORD"] = "111Vq63HN57f"
os.environ["DATABASE_HOST"] = "streetlives-prod.cd1mqmjnwg1v.us-east-1.rds.amazonaws.com"
os.environ["DATABASE_PORT"] = "5432"

In [3]:
security = HTTPBasic()

conn = psycopg2.connect(
    dbname=os.environ.get('DATABASE_NAME'),
    user=os.environ.get('DATABASE_USER'),
    password=os.environ.get('DATABASE_PASSWORD'),
    host=os.environ.get('DATABASE_HOST'),
    port=os.environ.get('DATABASE_PORT'),
)

# Scrape one frangrance (Bal d'afrique)

In [ ]:
scraper = FragranticaScraper()

url = "https://www.fragrantica.com/perfume/Byredo/Bal-d-Afrique-6458.html"
data = scraper.scrape_perfume_details(url)

In [ ]:
print(data['top_notes'])
print(data['middle_notes'])
print(data['base_notes'])

In [ ]:
urls = scraper.get_brand_urls("https://www.fragrantica.com/designers/Byredo.html")
print(urls[:5])  # check first 5

In [ ]:
data = scraper.scrape_perfume_details(urls[88])
print(data['product_description'])

print(data['gender'])

print(data['perfumer'])
print(data['main_accords'])
print(data['gender'])

In [ ]:
for url in urls[:5]:
    data = scraper.scrape_perfume_details(url)
    print(data['product_name'])
    print(data['top_notes'])
    print("---")

In [ ]:
data = scraper.scrape_perfume_details(urls[8])
print((data['product_description']))

# Scrape all of Byredo

In [ ]:
import time

results = []

for i, url in enumerate(urls):
    print(f"Scraping {i+1}/{len(urls)}: {url}")
    
    data = scraper.scrape_perfume_details(url)
    
    if data:
        results.append(data)
    
    # random delay between 3-7 seconds
    delay = random.uniform(3, 7)
    print(f"Waiting {delay:.1f} seconds...")
    time.sleep(delay)

print(f"\nDone! Scraped {len(results)} perfumes")
df = pd.DataFrame(results)
df.head()

In [ ]:
df_byredo = df[df['brand_name'] == 'Byredo']

In [ ]:
df_byredo.to_csv('byredo_data.csv', index=False)

# Scraping LV

In [2]:
scraper = FragranticaScraper()
lv_urls = scraper.get_brand_urls("https://www.fragrantica.com/designers/Louis-Vuitton.html")
print(f"Found {len(lv_urls)} Louis Vuitton perfumes")

🔍 Getting perfume URLs from: https://www.fragrantica.com/designers/Louis-Vuitton.html
✅ Found 97 perfumes
Found 97 Louis Vuitton perfumes

In [3]:
data = scraper.scrape_perfume_details(lv_urls[2])
print(data['product_description'])

print(data['gender'])
print(data['perfumer'])
print(data['perfumer'])
print(data['notes'])
print(data['main_accords'])
print(data['release_date'])

🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Rain-Tea-115406.html
Rain TeabyLouis Vuittonis a fragrance for women and men. This is a new fragrance.Rain Teawas launched in 2025. The nose behind this fragrance is Jacques Cavallier Belletrud. The fragrance features Tea, Lemongrass, Rose, Magnolia and Woody Notes.Rain Tea by Louis Vuitton is a unisex fragrance announced as part of the Journey to China collection. It is presented in a pastel mint green lacquered bottle with a salmon pink cap. Official note details and concentration have not been disclosed; the collection is planned to launch on October 17, 2025.
for women and men
Jacques Cavallier Belletrud
Jacques Cavallier Belletrud
Tea, Lemongrass, Rose, Magnolia, Woody Notes
citrus, fresh spicy, green, fresh
2025

## All of LV

In [5]:
results_lv = []

for i, url in enumerate(lv_urls):
    print(f"Scraping {i+1}/{len(lv_urls)}: {url}")
    
    data = scraper.scrape_perfume_details(url)
    
    if data:
        results_lv.append(data)
    
    delay = random.uniform(3, 7)
    print(f"Waiting {delay:.1f} seconds...")
    time.sleep(delay)

print(f"\nDone! Scraped {len(results_lv)} perfumes")
df_lv = pd.DataFrame(results_lv)
df_lv.head()

Scraping 1/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Ink-Mark-115407.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Ink-Mark-115407.html
Waiting 6.3 seconds...
Scraping 2/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Moon-Tale-115408.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Moon-Tale-115408.html
Waiting 5.3 seconds...
Scraping 3/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Rain-Tea-115406.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Rain-Tea-115406.html
Waiting 5.6 seconds...
Scraping 4/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Cosmic-Cloud-68355.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Cosmic-Cloud-68355.html
Waiting 3.5 seconds...
Scraping 5/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Dancing-Blossom-68358.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Dancing-Blossom-68358.html
Waiting 6.0 seconds...
Scraping 6/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Fantasmagory-116625.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Fantasmagory-116625.html
Waiting 5.3 seconds...
Scraping 7/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Myriad-85363.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Myriad-85363.html
Waiting 6.1 seconds...
Scraping 8/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Rhapsody-68359.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Rhapsody-68359.html
Waiting 5.5 seconds...
Scraping 9/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Stellar-Times-68356.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Stellar-Times-68356.html
Waiting 3.3 seconds...
Scraping 10/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Symphony-68357.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Symphony-68357.html
Waiting 5.3 seconds...
Scraping 11/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Afternoon-Swim-53947.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Afternoon-Swim-53947.html
Waiting 4.9 seconds...
Scraping 12/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Ambre-Levant-122775.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Ambre-Levant-122775.html
Waiting 5.3 seconds...
Scraping 13/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Apogee-40498.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Apogee-40498.html
Waiting 6.0 seconds...
Scraping 14/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Attrape-Reves-51016.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Attrape-Reves-51016.html
Waiting 3.8 seconds...
Scraping 15/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Au-Hasard-49756.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Au-Hasard-49756.html
Waiting 6.3 seconds...
Scraping 16/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Cactus-Garden-53946.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Cactus-Garden-53946.html
Waiting 5.0 seconds...
Scraping 17/97: https://www.fragrantica.com/perfume/Louis-Vuitton/California-Dream-60388.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/California-Dream-60388.html
Waiting 6.3 seconds...
Scraping 18/97: https://www.fragrantica.com/perfume/Louis-Vuitton/City-Of-Stars-73344.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/City-Of-Stars-73344.html
Waiting 4.3 seconds...
Scraping 19/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Coeur-Battant-57129.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Coeur-Battant-57129.html
Waiting 3.3 seconds...
Scraping 20/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Contre-Moi-40501.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Contre-Moi-40501.html
Waiting 6.8 seconds...
Scraping 21/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Dans-la-Peau-40500.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Dans-la-Peau-40500.html
Waiting 6.2 seconds...
Scraping 22/97: https://www.fragrantica.com/perfume/Louis-Vuitton/eLVes-104087.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/eLVes-104087.html
Waiting 6.9 seconds...
Scraping 23/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Etoile-Filante-64314.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Etoile-Filante-64314.html
Waiting 6.5 seconds...
Scraping 24/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Fleur-du-Desert-73006.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Fleur-du-Desert-73006.html
Waiting 5.9 seconds...
Scraping 25/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Heures-d-Absence-59485.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Heures-d-Absence-59485.html
Waiting 5.3 seconds...
Scraping 26/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Imagination-67370.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Imagination-67370.html
Waiting 6.7 seconds...
Scraping 27/97: https://www.fragrantica.com/perfume/Louis-Vuitton/L-Immensite-49751.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/L-Immensite-49751.html
Waiting 6.1 seconds...
Scraping 28/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Le-Jour-se-Leve-48305.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Le-Jour-se-Leve-48305.html
Waiting 4.5 seconds...
Scraping 29/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Les-Sables-Roses-55040.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Les-Sables-Roses-55040.html
Waiting 6.2 seconds...
Scraping 30/97: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-Lovers-93785.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-Lovers-93785.html
Waiting 4.1 seconds...
Scraping 31/97: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-x-TM-Spell-On-You-107114.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-x-TM-Spell-On-You-107114.html
Waiting 3.9 seconds...
Scraping 32/97: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-x-TM-Spell-On-You-V-2-107115.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/LV-x-TM-Spell-On-You-V-2-107115.html
Waiting 5.3 seconds...
Scraping 33/97: https://www.fragrantica.com/perfume/Louis-Vuitton/LVERS-Copper-Edition-108426.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/LVERS-Copper-Edition-108426.html
Waiting 5.7 seconds...
Scraping 34/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Matiere-Noire-40496.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Matiere-Noire-40496.html
Waiting 4.0 seconds...
Scraping 35/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Meteore-62251.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Meteore-62251.html
Waiting 3.4 seconds...
Scraping 36/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Mille-Feux-40497.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Mille-Feux-40497.html
Waiting 4.3 seconds...
Scraping 37/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-Attrape-Reves-122038.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-Attrape-Reves-122038.html
Waiting 5.2 seconds...
Scraping 38/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-eLVes-122132.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-eLVes-122132.html
Waiting 4.2 seconds...
Scraping 39/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-Imagination-122037.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Monogram-Imagination-122037.html
Waiting 4.7 seconds...
Scraping 40/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Nouveau-Monde-49753.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Nouveau-Monde-49753.html
Waiting 4.6 seconds...
Scraping 41/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Nuit-de-Feu-60031.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Nuit-de-Feu-60031.html
Waiting 5.3 seconds...
Scraping 42/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Ombre-Nomade-49755.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Ombre-Nomade-49755.html
Waiting 6.5 seconds...
Scraping 43/97: https://www.fragrantica.com/perfume/Louis-Vuitton/On-The-Beach-66060.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/On-The-Beach-66060.html
Waiting 5.3 seconds...
Scraping 44/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Orage-49752.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Orage-49752.html
Waiting 4.0 seconds...
Scraping 45/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Pacific-Chill-81423.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Pacific-Chill-81423.html
Waiting 3.8 seconds...
Scraping 46/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Ambre-90204.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Ambre-90204.html
Waiting 4.6 seconds...
Scraping 47/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Oud-66436.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Oud-66436.html
Waiting 3.8 seconds...
Scraping 48/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Santal-90205.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Pur-Santal-90205.html
Waiting 6.2 seconds...
Scraping 49/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Rose-des-Vents-40495.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Rose-des-Vents-40495.html
Waiting 3.4 seconds...
Scraping 50/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Spell-On-You-68960.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Spell-On-You-68960.html
Waiting 6.9 seconds...
Scraping 51/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Sun-Song-53945.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Sun-Song-53945.html
Waiting 3.8 seconds...
Scraping 52/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Sun-Song-2025-107116.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Sun-Song-2025-107116.html
Waiting 3.4 seconds...
Scraping 53/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Sur-la-Route-49754.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Sur-la-Route-49754.html
Waiting 4.8 seconds...
Scraping 54/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Turbulences-40499.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Turbulences-40499.html
Waiting 6.6 seconds...
Scraping 55/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Eau-de-Voyage-39153.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Eau-de-Voyage-39153.html
Waiting 5.6 seconds...
Scraping 56/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Heures-d-Absence-1927-39152.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Heures-d-Absence-1927-39152.html
Waiting 4.8 seconds...
Scraping 57/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Je-Tu-Il-39155.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Je-Tu-Il-39155.html
Waiting 4.7 seconds...
Scraping 58/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Reminiscences-39154.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Reminiscences-39154.html
Waiting 6.7 seconds...
Scraping 59/97: https://www.fragrantica.com/perfume/Louis-Vuitton/Sur-la-Route-vintage-39156.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Louis-Vuitton/Sur-la-Route-vintage-39156.html
Waiting 5.9 seconds...
Scraping 60/97: https://www.fragrantica.com/perfume/Dior/Hypnotic-Poison-219.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Dior/Hypnotic-Poison-219.html
Waiting 6.3 seconds...
Scraping 61/97: https://www.fragrantica.com/perfume/Armaf/Catwalk-87098.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Armaf/Catwalk-87098.html
Waiting 4.1 seconds...
Scraping 62/97: https://www.fragrantica.com/perfume/Le-Falcone-Perfumes/Juman-Precious-122741.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Le-Falcone-Perfumes/Juman-Precious-122741.html
Waiting 3.9 seconds...
Scraping 63/97: https://www.fragrantica.com/perfume/Elizabeth-Arden/Green-Tea-83.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Elizabeth-Arden/Green-Tea-83.html
Waiting 3.8 seconds...
Scraping 64/97: https://www.fragrantica.com/perfume/Parfums-de-Marly/Percival-51037.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Parfums-de-Marly/Percival-51037.html
Waiting 5.5 seconds...
Scraping 65/97: https://www.fragrantica.com/perfume/Les-Folies-Du-Parfum/Acqua-Tofana-90831.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Les-Folies-Du-Parfum/Acqua-Tofana-90831.html
Waiting 5.4 seconds...
Scraping 66/97: https://www.fragrantica.com/perfume/BDK-Parfums/Gris-Charnel-57038.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/BDK-Parfums/Gris-Charnel-57038.html
Waiting 5.3 seconds...
Scraping 67/97: https://www.fragrantica.com/perfume/Ex-Nihilo/Blue-Talisman-84224.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Ex-Nihilo/Blue-Talisman-84224.html
Waiting 3.7 seconds...
Scraping 68/97: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Scandal-Pour-Homme-Le-Parfum-74915.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Scandal-Pour-Homme-Le-Parfum-74915.html
Waiting 4.5 seconds...
Scraping 69/97: https://www.fragrantica.com/perfume/Kayali-Fragrances/Yum-Pistachio-Gelato-33-79846.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Kayali-Fragrances/Yum-Pistachio-Gelato-33-79846.html
Waiting 4.3 seconds...
Scraping 70/97: https://www.fragrantica.com/perfume/Grandeur/Iconic-Nuit-Pour-Homme-99213.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Grandeur/Iconic-Nuit-Pour-Homme-99213.html
Waiting 5.7 seconds...
Scraping 71/97: https://www.fragrantica.com/perfume/Commodity/Milk-69191.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Commodity/Milk-69191.html
Waiting 4.7 seconds...
Scraping 72/97: https://www.fragrantica.com/perfume/Moresque/Fiore-di-Portofino-41027.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Moresque/Fiore-di-Portofino-41027.html
Waiting 5.7 seconds...
Scraping 73/97: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-Absolu-101529.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-Absolu-101529.html
Waiting 6.0 seconds...
Scraping 74/97: https://www.fragrantica.com/perfume/Fragrance-Du-Bois/Lucius-Maximus-128309.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Fragrance-Du-Bois/Lucius-Maximus-128309.html
Waiting 5.2 seconds...
Scraping 75/97: https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-75805.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-75805.html
Waiting 5.7 seconds...
Scraping 76/97: https://www.fragrantica.com/perfume/French-Avenue/Liquid-Brun-94713.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/French-Avenue/Liquid-Brun-94713.html
Waiting 4.8 seconds...
Scraping 77/97: https://www.fragrantica.com/perfume/Giorgio-Armani/Emporio-Armani-Stronger-With-You-Intensely-52802.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Giorgio-Armani/Emporio-Armani-Stronger-With-You-Intensely-52802.html
Waiting 3.5 seconds...
Scraping 78/97: https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-Qahwa-88175.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-Qahwa-88175.html
Waiting 5.1 seconds...
Scraping 79/97: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Le-Parfum-61856.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Le-Parfum-61856.html
Waiting 6.8 seconds...
Scraping 80/97: https://www.fragrantica.com/perfume/Afnan/Supremacy-Collector-s-Edition-Pour-Homme-98689.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Afnan/Supremacy-Collector-s-Edition-Pour-Homme-98689.html
Waiting 5.8 seconds...
Scraping 81/97: https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html
Waiting 6.6 seconds...
Scraping 82/97: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-81642.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-81642.html
Waiting 6.9 seconds...
Scraping 83/97: https://www.fragrantica.com/perfume/By-Kilian/Angels-Share-62615.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/By-Kilian/Angels-Share-62615.html
Waiting 3.0 seconds...
Scraping 84/97: https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Intense-Man-34696.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Armaf/Club-de-Nuit-Intense-Man-34696.html
Waiting 6.5 seconds...
Scraping 85/97: https://www.fragrantica.com/perfume/Xerjoff/XJ-1861-Naxos-30529.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Xerjoff/XJ-1861-Naxos-30529.html
Waiting 6.2 seconds...
Scraping 86/97: https://www.fragrantica.com/perfume/French-Avenue/Vulcan-Feu-105520.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/French-Avenue/Vulcan-Feu-105520.html
Waiting 5.9 seconds...
Scraping 87/97: https://www.fragrantica.com/perfume/Maison-Martin-Margiela/By-the-Fireplace-31623.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Maison-Martin-Margiela/By-the-Fireplace-31623.html
Waiting 5.5 seconds...
Scraping 88/97: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Beau-Le-Parfum-72158.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Beau-Le-Parfum-72158.html
Waiting 6.8 seconds...
Scraping 89/97: https://www.fragrantica.com/perfume/Yves-Saint-Laurent/MYSLF-Eau-de-Parfum-84094.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Yves-Saint-Laurent/MYSLF-Eau-de-Parfum-84094.html
Waiting 6.0 seconds...

,product_url,product_name,brand_name,rating,number_of_ratings,product_description,release_date,top_notes,middle_notes,base_notes,notes,main_accords,perfumer,product_images,gender,longevity,sillage,scraped_at,source
0,https://www.fragrantica.com/perfume/Louis-Vuit...,Ink Mark Louis Vuittonfor women and men,Louis Vuitton,4.33,241,Ink MarkbyLouis Vuittonis a Oriental Woody fra...,2025,N/A,N/A,N/A,"Sandalwood, Amber, Incense","woody, powdery, warm spicy, aromatic",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:25,Fragrantica
1,https://www.fragrantica.com/perfume/Louis-Vuit...,Moon Tale Louis Vuittonfor women and men,Louis Vuitton,4.50,254,Moon TalebyLouis Vuittonis a fragrance for wom...,2025,N/A,N/A,N/A,"Peony, Raspberry, Jasmine Sambac, Magnolia, Ro...","floral, fruity, white floral, fresh",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:37,Fragrantica
2,https://www.fragrantica.com/perfume/Louis-Vuit...,Rain Tea Louis Vuittonfor women and men,Louis Vuitton,4.43,316,Rain TeabyLouis Vuittonis a fragrance for wome...,2025,N/A,N/A,N/A,"Tea, Lemongrass, Rose, Magnolia, Woody Notes","citrus, fresh spicy, green, fresh",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:46,Fragrantica
3,https://www.fragrantica.com/perfume/Louis-Vuit...,Cosmic Cloud Louis Vuittonfor women and men,Louis Vuitton,3.70,338,Cosmic CloudbyLouis Vuittonis a Chypre Fruity ...,2021,N/A,N/A,N/A,"Musk, Black Currant, Bergamot, Patchouli","musky, powdery, fruity, animalic",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:57,Fragrantica
4,https://www.fragrantica.com/perfume/Louis-Vuit...,Dancing Blossom Louis Vuittonfor women and men,Louis Vuitton,4.03,284,Dancing BlossombyLouis Vuittonis a Floral frag...,2021,N/A,N/A,N/A,"May Rose, Jasmine Sambac, Tuberose, Osmanthus","white floral, rose, floral, tuberose",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:55:05,Fragrantica

In [6]:

df_lv_final= df_lv[df_lv['brand_name'] == 'Louis Vuitton']

df_lv

,product_url,product_name,brand_name,rating,number_of_ratings,product_description,release_date,top_notes,middle_notes,base_notes,notes,main_accords,perfumer,product_images,gender,longevity,sillage,scraped_at,source
0,https://www.fragrantica.com/perfume/Louis-Vuit...,Ink Mark Louis Vuittonfor women and men,Louis Vuitton,4.33,241,Ink MarkbyLouis Vuittonis a Oriental Woody fra...,2025,N/A,N/A,N/A,"Sandalwood, Amber, Incense","woody, powdery, warm spicy, aromatic",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:25,Fragrantica
1,https://www.fragrantica.com/perfume/Louis-Vuit...,Moon Tale Louis Vuittonfor women and men,Louis Vuitton,4.50,254,Moon TalebyLouis Vuittonis a fragrance for wom...,2025,N/A,N/A,N/A,"Peony, Raspberry, Jasmine Sambac, Magnolia, Ro...","floral, fruity, white floral, fresh",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:37,Fragrantica
2,https://www.fragrantica.com/perfume/Louis-Vuit...,Rain Tea Louis Vuittonfor women and men,Louis Vuitton,4.43,316,Rain TeabyLouis Vuittonis a fragrance for wome...,2025,N/A,N/A,N/A,"Tea, Lemongrass, Rose, Magnolia, Woody Notes","citrus, fresh spicy, green, fresh",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:46,Fragrantica
3,https://www.fragrantica.com/perfume/Louis-Vuit...,Cosmic Cloud Louis Vuittonfor women and men,Louis Vuitton,3.70,338,Cosmic CloudbyLouis Vuittonis a Chypre Fruity ...,2021,N/A,N/A,N/A,"Musk, Black Currant, Bergamot, Patchouli","musky, powdery, fruity, animalic",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:54:57,Fragrantica
4,https://www.fragrantica.com/perfume/Louis-Vuit...,Dancing Blossom Louis Vuittonfor women and men,Louis Vuitton,4.03,284,Dancing BlossombyLouis Vuittonis a Floral frag...,2021,N/A,N/A,N/A,"May Rose, Jasmine Sambac, Tuberose, Osmanthus","white floral, rose, floral, tuberose",Jacques Cavallier Belletrud,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 09:55:05,Fragrantica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,https://www.fragrantica.com/perfume/Valentino/...,Valentino Uomo Born In Roma Intense Valentinof...,Valentino,4.52,10846,Valentino Uomo Born In Roma IntensebyValentino...,2023,Vanilla,Lavender,Vetiver,N/A,"lavender, vanilla, aromatic, woody",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 10:10:19,Fragrantica
93,https://www.fragrantica.com/perfume/Tom-Ford/T...,Tobacco Vanille Tom Fordfor women and men,Tom Ford,4.18,30413,Tobacco VanillebyTom Fordis a Oriental Spicy f...,2007,"Tobacco Leaf, Spicy Notes","Vanilla, Cacao, Tonka Bean, Tobacco Blossom","Dried Fruits, Woody Notes",N/A,"vanilla, sweet, tobacco, warm spicy",Olivier Gillotin,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 10:10:28,Fragrantica
94,https://www.fragrantica.com/perfume/Maison-Mar...,Jazz Club Maison Martin Margielafor men,Maison Martin Margiela,4.20,20368,Jazz ClubbyMaison Martin Margielais a Leather ...,2013,"Pink Pepper, Neroli, Lemon","Rum, Java vetiver oil, Clary Sage","Tobacco Leaf, Vanilla Bean, Styrax",N/A,"tobacco, sweet, vanilla, rum",Alienor Massenet,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 10:10:38,Fragrantica
95,https://www.fragrantica.com/perfume/Creed/Aven...,Aventus Creedfor men,Creed,4.32,27073,AventusbyCreedis a Chypre Fruity fragrance for...,2010,"Bergamot, Black Currant, Apple, Lemon, Pink Pe...","Pineapple, Patchouli, Moroccan Jasmine","Birch, Musk, oak moss, Cedarwood, Ambroxan",N/A,"fruity, sweet, woody, leather",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 10:10:48,Fragrantica
96,https://www.fragrantica.com/perfume/Parfums-de...,Althaïr Parfums de Marlyfor men,Parfums de Marly,4.40,10491,AlthaïrbyParfums de Marlyis a Oriental Vanilla...,2023,"Cinnamon, Orange Blossom, Cardamom, Bergamot","Bourbon Vanilla, elemi","Praline, Musk, Ambroxan, Guaiac Wood, Tonka, C...",N/A,"sweet, vanilla, warm spicy, cinnamon",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 10:11:01,Fragrantica

In [ ]:
df_lv_final

In [9]:
df_lv_final.to_csv('lv_data.csv', index=False)

# Scrape Guerlain

In [11]:
scraper = FragranticaScraper()
guerlain_urls = scraper.get_brand_urls("https://www.fragrantica.com/designers/Guerlain.html")
print(f"Found {len(lv_urls)} guelain perfumes")

🔍 Getting perfume URLs from: https://www.fragrantica.com/designers/Guerlain.html
✅ Found 616 perfumes
Found 97 guelain perfumes

In [ ]:
data = scraper.scrape_perfume_details(guerlain_urls[2])
print(data['product_description'])

print(data['gender'])
print(data['perfumer'])
print(data['notes'])
print(data['main_accords'])
print(data['release_date'])

🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Apres-l-Ondee-13.html
Apres l'OndeebyGuerlainis a Oriental Floral fragrance for women.Apres l'Ondeewas launched in 1906. The nose behind this fragrance is Jacques Guerlain. Top notes are Anise, Cassia, Neroli, Bergamot and Lemon; middle notes are Violet, Orris Root, Mimosa, Carnation, Sandalwood, Rose, Ylang-Ylang, Vetiver and Jasmine; base notes are Iris, Heliotrope, Vanilla, Musk, Benzoin, Styrax and Amber.Apres l\'Ondee was created by Jacques Guerlain in 1906. It is a beautiful, delicate combination of orange blossom and violet, with spicy anis note. Smell of a spring-time garden after a downpour, smell of wet leaves and flowers warmed by the sunshine. The heart is composed of spicy carnation and violet, not traditionally sweet in this composition. The base notes include luxurious iris and soft vanilla touch.
for women
Jacques Guerlain
Jacques Guerlain
N/A
powdery, violet, iris, floral
1906

In [13]:
results_guerlain = []

for i, url in enumerate(guerlain_urls):
    print(f"Scraping {i+1}/{len(guerlain_urls)}: {url}")
    
    data = scraper.scrape_perfume_details(url)
    
    if data:
        results_guerlain.append(data)
    
    delay = random.uniform(3, 7)
    print(f"Waiting {delay:.1f} seconds...")
    time.sleep(delay)

print(f"\nDone! Scraped {len(results_guerlain)} perfumes")
df_guerlain = pd.DataFrame(results_guerlain)
df_guerlain.head()

Scraping 1/616: https://www.fragrantica.com/perfume/Guerlain/180-Ans-de-Creations-1828-2008-33479.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/180-Ans-de-Creations-1828-2008-33479.html
Waiting 4.4 seconds...
Scraping 2/616: https://www.fragrantica.com/perfume/Guerlain/190-Ans-de-Creation-1828-2018-58561.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/190-Ans-de-Creation-1828-2018-58561.html
Waiting 4.2 seconds...
Scraping 3/616: https://www.fragrantica.com/perfume/Guerlain/Apres-l-Ondee-13.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Apres-l-Ondee-13.html
Waiting 5.8 seconds...
Scraping 4/616: https://www.fragrantica.com/perfume/Guerlain/Attrape-Coeur-51369.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Attrape-Coeur-51369.html
Waiting 6.4 seconds...
Scraping 5/616: https://www.fragrantica.com/perfume/Guerlain/Beau-Rivage-Palace-130977.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Beau-Rivage-Palace-130977.html
Waiting 6.5 seconds...
Scraping 6/616: https://www.fragrantica.com/perfume/Guerlain/Belle-Epoque-Limited-Edition-43292.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Belle-Epoque-Limited-Edition-43292.html
Waiting 6.5 seconds...
Scraping 7/616: https://www.fragrantica.com/perfume/Guerlain/Bouquet-de-Faunes-30807.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Bouquet-de-Faunes-30807.html
Waiting 5.1 seconds...
Scraping 8/616: https://www.fragrantica.com/perfume/Guerlain/Bouquet-de-Paris-57878.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Bouquet-de-Paris-57878.html
Waiting 3.7 seconds...
Scraping 9/616: https://www.fragrantica.com/perfume/Guerlain/Cheval-Blanc-98237.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Cheval-Blanc-98237.html
Waiting 3.1 seconds...
Scraping 10/616: https://www.fragrantica.com/perfume/Guerlain/Cheval-Blanc-St-Tropez-113887.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Cheval-Blanc-St-Tropez-113887.html
Waiting 4.3 seconds...
Scraping 11/616: https://www.fragrantica.com/perfume/Guerlain/Chypre-de-Paris-41629.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Chypre-de-Paris-41629.html
Waiting 3.4 seconds...
Scraping 12/616: https://www.fragrantica.com/perfume/Guerlain/Cologne-du-68-4347.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Cologne-du-68-4347.html
Waiting 6.2 seconds...
Scraping 13/616: https://www.fragrantica.com/perfume/Guerlain/Colours-of-Love-68.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Colours-of-Love-68.html
Waiting 3.7 seconds...
Scraping 14/616: https://www.fragrantica.com/perfume/Guerlain/Coriolan-2288.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Coriolan-2288.html
Waiting 3.3 seconds...
Scraping 15/616: https://www.fragrantica.com/perfume/Guerlain/Cuir-de-Russie-29336.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Cuir-de-Russie-29336.html
Waiting 6.3 seconds...
Scraping 16/616: https://www.fragrantica.com/perfume/Guerlain/Derby-Vintage-5396.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Derby-Vintage-5396.html
Waiting 6.8 seconds...
Scraping 17/616: https://www.fragrantica.com/perfume/Guerlain/Eau-de-Coton-93131.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Eau-de-Coton-93131.html
Waiting 6.1 seconds...
Scraping 18/616: https://www.fragrantica.com/perfume/Guerlain/Fol-Arome-42901.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Fol-Arome-42901.html
Waiting 4.2 seconds...
Scraping 19/616: https://www.fragrantica.com/perfume/Guerlain/Garden-Sensuel-3754.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Garden-Sensuel-3754.html
Waiting 6.4 seconds...
Scraping 20/616: https://www.fragrantica.com/perfume/Guerlain/Guerlain-Le-Parfum-du-68-21752.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Guerlain-Le-Parfum-du-68-21752.html
Waiting 6.9 seconds...
Scraping 21/616: https://www.fragrantica.com/perfume/Guerlain/Guet-Apens-5750.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Guet-Apens-5750.html
Waiting 6.1 seconds...
Scraping 22/616: https://www.fragrantica.com/perfume/Guerlain/Jardin-de-l-Elysee-129308.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Jardin-de-l-Elysee-129308.html
Waiting 3.2 seconds...
Scraping 23/616: https://www.fragrantica.com/perfume/Guerlain/Jardins-de-Bagatelle-3809.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Jardins-de-Bagatelle-3809.html
Waiting 6.0 seconds...
Scraping 24/616: https://www.fragrantica.com/perfume/Guerlain/Kadine-25160.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Kadine-25160.html
Waiting 4.3 seconds...
Scraping 25/616: https://www.fragrantica.com/perfume/Guerlain/L-Heure-Blanche-58941.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/L-Heure-Blanche-58941.html
Waiting 3.7 seconds...
Scraping 26/616: https://www.fragrantica.com/perfume/Guerlain/L-Heure-Bleue-Yves-Klein-Edition-76819.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/L-Heure-Bleue-Yves-Klein-Edition-76819.html
Waiting 4.9 seconds...
Scraping 27/616: https://www.fragrantica.com/perfume/Guerlain/Le-Bouquet-de-la-Mariee-29612.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Le-Bouquet-de-la-Mariee-29612.html
Waiting 4.3 seconds...
Scraping 28/616: https://www.fragrantica.com/perfume/Guerlain/Le-Bouquet-de-la-Reine-35522.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Le-Bouquet-de-la-Reine-35522.html
Waiting 3.3 seconds...
Scraping 29/616: https://www.fragrantica.com/perfume/Guerlain/Le-Plus-Beau-Jour-de-Ma-Vie-30213.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Le-Plus-Beau-Jour-de-Ma-Vie-30213.html
Waiting 6.4 seconds...
Scraping 30/616: https://www.fragrantica.com/perfume/Guerlain/Les-Secrets-de-Sophie-7222.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Les-Secrets-de-Sophie-7222.html
Waiting 5.0 seconds...
Scraping 31/616: https://www.fragrantica.com/perfume/Guerlain/Love-is-All-45.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Love-is-All-45.html
Waiting 6.9 seconds...
Scraping 32/616: https://www.fragrantica.com/perfume/Guerlain/Lui-45660.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Lui-45660.html
Waiting 5.1 seconds...
Scraping 33/616: https://www.fragrantica.com/perfume/Guerlain/Mahora-2660.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Mahora-2660.html
Waiting 6.5 seconds...
Scraping 34/616: https://www.fragrantica.com/perfume/Guerlain/Marie-Claire-15487.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Marie-Claire-15487.html
Waiting 4.0 seconds...
Scraping 35/616: https://www.fragrantica.com/perfume/Guerlain/Meteorites-4045.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Meteorites-4045.html
Waiting 4.5 seconds...
Scraping 36/616: https://www.fragrantica.com/perfume/Guerlain/Meteorites-Le-Parfum-49587.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Meteorites-Le-Parfum-49587.html
Waiting 3.7 seconds...
Scraping 37/616: https://www.fragrantica.com/perfume/Guerlain/Mitsouko-Eau-de-Parfum-113910.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Mitsouko-Eau-de-Parfum-113910.html
Waiting 5.0 seconds...
Scraping 38/616: https://www.fragrantica.com/perfume/Guerlain/Mon-Exclusif-30944.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Mon-Exclusif-30944.html
Waiting 6.8 seconds...
Scraping 39/616: https://www.fragrantica.com/perfume/Guerlain/Mouchoir-de-Monsieur-3943.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Mouchoir-de-Monsieur-3943.html
Waiting 4.9 seconds...
Scraping 40/616: https://www.fragrantica.com/perfume/Guerlain/Ne-m-Oubliez-Pas-32355.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Ne-m-Oubliez-Pas-32355.html
Waiting 5.3 seconds...
Scraping 41/616: https://www.fragrantica.com/perfume/Guerlain/Ode-22958.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Ode-22958.html
Waiting 5.5 seconds...
Scraping 42/616: https://www.fragrantica.com/perfume/Guerlain/Oud-Sensuel-38414.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Oud-Sensuel-38414.html
Waiting 4.8 seconds...
Scraping 43/616: https://www.fragrantica.com/perfume/Guerlain/Parure-47.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Parure-47.html
Waiting 6.7 seconds...
Scraping 44/616: https://www.fragrantica.com/perfume/Guerlain/Petit-Guerlain-2620.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Petit-Guerlain-2620.html
Waiting 5.3 seconds...
Scraping 45/616: https://www.fragrantica.com/perfume/Guerlain/Philtre-d-Amour-2655.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Philtre-d-Amour-2655.html
Waiting 4.4 seconds...
Scraping 46/616: https://www.fragrantica.com/perfume/Guerlain/Place-Rouge-18983.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Place-Rouge-18983.html
Waiting 5.8 seconds...
Scraping 47/616: https://www.fragrantica.com/perfume/Guerlain/Plus-Que-Jamais-9417.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Plus-Que-Jamais-9417.html
Waiting 3.1 seconds...
Scraping 48/616: https://www.fragrantica.com/perfume/Guerlain/Precious-Heart-2619.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Precious-Heart-2619.html
Waiting 4.2 seconds...
Scraping 49/616: https://www.fragrantica.com/perfume/Guerlain/Purple-Fantasy-6324.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Purple-Fantasy-6324.html
Waiting 3.6 seconds...
Scraping 50/616: https://www.fragrantica.com/perfume/Guerlain/Quand-Vient-La-Pluie-2618.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Quand-Vient-La-Pluie-2618.html
Waiting 3.6 seconds...
Scraping 51/616: https://www.fragrantica.com/perfume/Guerlain/Royal-Extract-II-60616.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Royal-Extract-II-60616.html
Waiting 4.1 seconds...
Scraping 52/616: https://www.fragrantica.com/perfume/Guerlain/Royal-Extract-III-117104.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Royal-Extract-III-117104.html
Waiting 3.5 seconds...
Scraping 53/616: https://www.fragrantica.com/perfume/Guerlain/Royal-Extrait-28844.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Royal-Extrait-28844.html
Waiting 3.6 seconds...
Scraping 54/616: https://www.fragrantica.com/perfume/Guerlain/Secret-Intention-3347.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Secret-Intention-3347.html
Waiting 3.1 seconds...
Scraping 55/616: https://www.fragrantica.com/perfume/Guerlain/Sous-le-Vent-5400.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Sous-le-Vent-5400.html
Waiting 3.5 seconds...
Scraping 56/616: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Eau-Sous-Le-Vent-5883.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Eau-Sous-Le-Vent-5883.html
Waiting 4.4 seconds...
Scraping 57/616: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Le-Parfum-24785.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Le-Parfum-24785.html
Waiting 4.7 seconds...
Scraping 58/616: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Voile-d-Ete-No-25-Quand-Vient-l-Ete-2615.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Terracotta-Voile-d-Ete-No-25-Quand-Vient-l-Ete-2615.html
Waiting 4.6 seconds...
Scraping 59/616: https://www.fragrantica.com/perfume/Guerlain/Voilette-de-Madame-11305.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Voilette-de-Madame-11305.html
Waiting 6.8 seconds...
Scraping 60/616: https://www.fragrantica.com/perfume/Guerlain/With-Love-2614.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/With-Love-2614.html
Waiting 4.5 seconds...
Scraping 61/616: https://www.fragrantica.com/perfume/Guerlain/Xi-an-65980.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Xi-an-65980.html
Waiting 3.1 seconds...
Scraping 62/616: https://www.fragrantica.com/perfume/Guerlain/Ambre-Samar-105007.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Ambre-Samar-105007.html
Waiting 3.2 seconds...
Scraping 63/616: https://www.fragrantica.com/perfume/Guerlain/Cuir-Intense-96469.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Cuir-Intense-96469.html
Waiting 4.6 seconds...
Scraping 64/616: https://www.fragrantica.com/perfume/Guerlain/Epices-Exquises-96473.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Epices-Exquises-96473.html
Waiting 3.1 seconds...
Scraping 65/616: https://www.fragrantica.com/perfume/Guerlain/Florabloom-Absolu-113077.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Florabloom-Absolu-113077.html
Waiting 5.7 seconds...
Scraping 66/616: https://www.fragrantica.com/perfume/Guerlain/Oud-Essentiel-96471.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Oud-Essentiel-96471.html
Waiting 5.5 seconds...
Scraping 67/616: https://www.fragrantica.com/perfume/Guerlain/Patchouli-Ardent-96472.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Patchouli-Ardent-96472.html
Waiting 4.6 seconds...
Scraping 68/616: https://www.fragrantica.com/perfume/Guerlain/Rose-Amira-90836.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Rose-Amira-90836.html
Waiting 6.9 seconds...
Scraping 69/616: https://www.fragrantica.com/perfume/Guerlain/Santal-Royal-96470.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Santal-Royal-96470.html
Waiting 4.7 seconds...
Scraping 70/616: https://www.fragrantica.com/perfume/Guerlain/Santal-Royal-Hair-Mist-96474.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Santal-Royal-Hair-Mist-96474.html
Waiting 4.3 seconds...
Scraping 71/616: https://www.fragrantica.com/perfume/Guerlain/Tabac-Sahara-120473.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Tabac-Sahara-120473.html
Waiting 4.1 seconds...
Scraping 72/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Angelique-Lilas-2088.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Angelique-Lilas-2088.html
Waiting 3.8 seconds...
Scraping 73/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Anisia-Bella-572.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Anisia-Bella-572.html
Waiting 4.3 seconds...
Scraping 74/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bergamote-Calabria-43596.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bergamote-Calabria-43596.html
Waiting 3.9 seconds...
Scraping 75/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-de-Mai-16034.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-de-Mai-16034.html
Waiting 5.9 seconds...
Scraping 76/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-Numero-1-8470.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-Numero-1-8470.html
Waiting 5.1 seconds...
Scraping 77/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-Numero-2-12481.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bouquet-Numero-2-12481.html
Waiting 6.8 seconds...
Scraping 78/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Cherry-Blossom-5741.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Cherry-Blossom-5741.html
Waiting 4.1 seconds...
Scraping 79/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Coconut-Fizz-53806.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Coconut-Fizz-53806.html
Waiting 3.5 seconds...
Scraping 80/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Figue-Iris-2636.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Figue-Iris-2636.html
Waiting 5.1 seconds...
Scraping 81/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Cherrysia-53804.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Cherrysia-53804.html
Waiting 5.5 seconds...
Scraping 82/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Cherrysia-Sakura-Collection-2020-58847.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Cherrysia-Sakura-Collection-2020-58847.html
Waiting 4.2 seconds...
Scraping 83/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Nerolia-573.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Nerolia-573.html
Waiting 3.7 seconds...
Scraping 84/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Nymphea-7967.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Nymphea-7967.html
Waiting 6.0 seconds...
Scraping 85/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Rosa-18061.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Rosa-18061.html
Waiting 3.1 seconds...
Scraping 86/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Salvaggia-66359.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Salvaggia-66359.html
Waiting 3.4 seconds...
Scraping 87/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-89854.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-89854.html
Waiting 6.6 seconds...
Scraping 88/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-Forte-89855.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-Forte-89855.html
Waiting 6.0 seconds...
Scraping 89/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Foliflora-65.html
🌸 Scraping perfume details from: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Foliflora-65.html
Waiting 6.5 seconds...
Scraping 90/616: https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Gentiana-58.html

,product_url,product_name,brand_name,rating,number_of_ratings,product_description,release_date,top_notes,middle_notes,base_notes,notes,main_accords,perfumer,product_images,gender,longevity,sillage,scraped_at,source
0,https://www.fragrantica.com/perfume/Guerlain/1...,180 Ans de Créations 1828-2008 Guerlainfor wom...,Guerlain,4.30,57,180 Ans de Créations 1828-2008byGuerlainis a O...,N/A,N/A,N/A,N/A,"Vanilla, Pink Pepper, Orange Blossom, Jasmine,...","white floral, citrus, vanilla, soft spicy",Jean-Paul Guerlain,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:14,Fragrantica
1,https://www.fragrantica.com/perfume/Guerlain/1...,190 Ans de Création 1828-2018 Guerlainfor wome...,Guerlain,4.36,56,190 Ans de Création 1828-2018byGuerlainis a Fl...,2018,N/A,N/A,N/A,"Benzoin, Orange Blossom, Almond, Ylang-Ylang, ...","amber, sweet, citrus, woody",Thierry Wasser,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:23,Fragrantica
2,https://www.fragrantica.com/perfume/Guerlain/A...,Apres l'Ondee Guerlainfor women,Guerlain,4.28,2409,Apres l'OndeebyGuerlainis a Oriental Floral fr...,1906,"Anise, Cassia, Neroli, Bergamot, Lemon","Violet, Orris Root, Mimosa, Carnation, Sandalw...","Iris, Heliotrope, Vanilla, Musk, Benzoin, Styr...",N/A,"powdery, violet, iris, floral",Jacques Guerlain,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women,N/A,N/A,2026-06-09 11:01:34,Fragrantica
3,https://www.fragrantica.com/perfume/Guerlain/A...,Attrape Coeur Guerlainfor women,Guerlain,4.27,60,Attrape CoeurbyGuerlainis a Oriental Floral fr...,2005,"Peach, Rose","Cinnamon, Violet, Iris, Tuberose, Jasmine","Vanilla, Amber, Sandalwood, Orris Root, Oakmos...",N/A,"powdery, woody, iris, warm spicy",Mathilde Laurent,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women,N/A,N/A,2026-06-09 11:01:45,Fragrantica
4,https://www.fragrantica.com/perfume/Guerlain/B...,Beau Rivage Palace Guerlainfor women and men,Guerlain,4.27,11,Beau Rivage PalacebyGuerlainis a Floral Woody ...,2026,"Bitter Almond, Petitgrain","Orange Blossom, Jasmine","Vanilla, Musk, Sandalwood, Guaiac Wood",N/A,"white floral, almond, sweet, nutty",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:56,Fragrantica

In [16]:
guerlain_final = df_guerlain[df_guerlain['brand_name'] == 'Guerlain']

guerlain_final

,product_url,product_name,brand_name,rating,number_of_ratings,product_description,release_date,top_notes,middle_notes,base_notes,notes,main_accords,perfumer,product_images,gender,longevity,sillage,scraped_at,source
0,https://www.fragrantica.com/perfume/Guerlain/1...,180 Ans de Créations 1828-2008 Guerlainfor wom...,Guerlain,4.30,57,180 Ans de Créations 1828-2008byGuerlainis a O...,N/A,N/A,N/A,N/A,"Vanilla, Pink Pepper, Orange Blossom, Jasmine,...","white floral, citrus, vanilla, soft spicy",Jean-Paul Guerlain,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:14,Fragrantica
1,https://www.fragrantica.com/perfume/Guerlain/1...,190 Ans de Création 1828-2018 Guerlainfor wome...,Guerlain,4.36,56,190 Ans de Création 1828-2018byGuerlainis a Fl...,2018,N/A,N/A,N/A,"Benzoin, Orange Blossom, Almond, Ylang-Ylang, ...","amber, sweet, citrus, woody",Thierry Wasser,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:23,Fragrantica
2,https://www.fragrantica.com/perfume/Guerlain/A...,Apres l'Ondee Guerlainfor women,Guerlain,4.28,2409,Apres l'OndeebyGuerlainis a Oriental Floral fr...,1906,"Anise, Cassia, Neroli, Bergamot, Lemon","Violet, Orris Root, Mimosa, Carnation, Sandalw...","Iris, Heliotrope, Vanilla, Musk, Benzoin, Styr...",N/A,"powdery, violet, iris, floral",Jacques Guerlain,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women,N/A,N/A,2026-06-09 11:01:34,Fragrantica
3,https://www.fragrantica.com/perfume/Guerlain/A...,Attrape Coeur Guerlainfor women,Guerlain,4.27,60,Attrape CoeurbyGuerlainis a Oriental Floral fr...,2005,"Peach, Rose","Cinnamon, Violet, Iris, Tuberose, Jasmine","Vanilla, Amber, Sandalwood, Orris Root, Oakmos...",N/A,"powdery, woody, iris, warm spicy",Mathilde Laurent,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women,N/A,N/A,2026-06-09 11:01:45,Fragrantica
4,https://www.fragrantica.com/perfume/Guerlain/B...,Beau Rivage Palace Guerlainfor women and men,Guerlain,4.27,11,Beau Rivage PalacebyGuerlainis a Floral Woody ...,2026,"Bitter Almond, Petitgrain","Orange Blossom, Jasmine","Vanilla, Musk, Sandalwood, Guaiac Wood",N/A,"white floral, almond, sweet, nutty",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for women and men,N/A,N/A,2026-06-09 11:01:56,Fragrantica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,https://www.fragrantica.com/perfume/Guerlain/L...,L’Homme Idéal Guerlainfor men,Guerlain,4.17,6360,L’Homme IdéalbyGuerlainis a Woody Aromatic fra...,2014,"Citruses, Bitter Orange, Rosemary, Orange Blossom","Almond, Tonka Bean","Leather, Cedar, Vetiver",N/A,"citrus, almond, aromatic, sweet",Thierry Wasser,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 11:52:21,Fragrantica
295,https://www.fragrantica.com/perfume/Guerlain/L...,L’Homme Idéal Cologne Guerlainfor men,Guerlain,4.34,4163,L’Homme Idéal ColognebyGuerlainis a Woody Arom...,2015,"Grapefruit, Orange, Bergamot, Pink Pepper","Almond, Neroli","Vetiver, White Musk",N/A,"citrus, almond, fresh spicy, aromatic",Thierry Wasser,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 11:52:33,Fragrantica
296,https://www.fragrantica.com/perfume/Guerlain/L...,L’Homme Idéal Cool Guerlainfor men,Guerlain,4.15,1231,L’Homme Idéal CoolbyGuerlainis a Aromatic Foug...,2019,"Mint, Bergamot, Orange, Anise","Almond, Water Notes, Neroli","Ambroxan, Vetiver, Patchouli",N/A,"green, aromatic, citrus, fresh spicy",Thierry Wasser,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 11:52:43,Fragrantica
297,https://www.fragrantica.com/perfume/Guerlain/L...,L’Homme Idéal Eau de Parfum Guerlainfor men,Guerlain,4.45,9962,L’Homme Idéal Eau de ParfumbyGuerlainis a Orie...,2016,"Almond, Spices, Lavender, Bergamot, Rosemary, ...","Cherry, Vanilla, Incense, Bulgarian Rose","Tonka Bean, Leather, Sandalwood",N/A,"sweet, cherry, vanilla, almond",N/A,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 11:52:57,Fragrantica
298,https://www.fragrantica.com/perfume/Guerlain/L...,L’Homme Idéal Platine Privé Guerlainfor men,Guerlain,4.43,1129,L’Homme Idéal Platine PrivébyGuerlainis a frag...,2023,"Grapefruit, Bergamot","Green Almond, Neroli","Musk, Vetiver",N/A,"citrus, aromatic, almond, fresh spicy",Delphine Jelk,https://fimgs.net/mdimg/perfume-thumbs/375x500...,for men,N/A,N/A,2026-06-09 11:53:08,Fragrantica

In [17]:
guerlain_final.to_csv('guerlain_data', index= False)